### ISSUE TITLE
Integrate darksky as a weather provider

### ISSUE THREAD

**Issue by BenFradet** [snowplow/scala-weather#42]
https://darksky.net/dev

**Comment by alexanderdean** [comment]
Interesting. I swear by Dark Sky on my phone.

**Comment by chuwy** [comment]
Good idea. We actually can come up with a decent list of weather providers as scala-weather never meant to be OWM-specific.

**Comment by BenFradet** [comment]
@asoltysik this is more of an exploratory ticket to check if there are better weather providers than the one we're currently using

**Comment by asoltysik** [comment]
I've checked out Dark Sky docs, here is a short summary of my observations:

- there is just one, less confusing, API for forecasts and history instead of separate like in OWM
- you can only get data from coordinates, no built-in geocoding
- there is just one endpoint - when there is no time provided it serves current weather and a week forecast; when provided time it either serves history or forecast for that date
- very simple pricing model and afaik it's quite popular in weather apps

AccuWeather is also really popular, but I couldn't find an API for historical data.

**Comment by BenFradet** [comment]
cool, changed the title :+1:

**Comment by asoltysik** [comment]
You want to see this on 0.4?
